refactor: Relocate Docker and env files
senchabot-dev/monorepo pull request #85
Opened 2023-04-26 23:33 UTC by sevilayerkan

- Docker compose and env.example files relocated to main directory.
- For prisma to run env.example file should stay in `/reflect` just now. 
- Because of these changes documentations also updated

2023-04-27 08:56 UTC, usirin commented on README.md
> +   ```
💯

2023-04-27 08:59 UTC, usirin commented on env.example
> +NEXT_PUBLIC_APP_CONTENT_STRING="All Bots and Stream overlays, Manage from one place! 100% Open source Discord and Twitch bot."
:( next .....................................................................................................................................

2023-04-27 10:58 UTC, durmusrasit commented on env.example
> +NEXT_PUBLIC_APP_NAME="Senchabot"
It would be good we remove nextjs related variables from the env.example in the main directory, Thanks!

2023-04-27 23:44 UTC, durmusrasit requested changes

2023-04-27 23:44 UTC, durmusrasit commented on docker-compose.yml
> +    container_name: senchabot_pql_dbcd
We can change it to `senchabot_psql_db` or `senchabot_db` etc.

2023-04-27 23:44 UTC, durmusrasit commented on env.example
>  # When adding additional env variables, the schema in /env/schema.mjs should be updated accordingly
We don't need this line. We can remove it

2023-05-06 18:56 UTC, sevilayerkan commented
I think this pr can be merged now. If there is any problem in latest commits please let me know

2023-05-06 20:11 UTC, durmusrasit commented on apps/reflect/README.md
> +5. For `Prisma` create a `.env` file based on the example file `env.example`
We can remove "For `Prisma`" because env.example is not just for Prisma

2023-05-06 20:37 UTC, durmusrasit approved these changes
This is an important PR for the setup phases of the Senchabot monorepo. Thanks a lot for this!

2023-05-06 20:37 UTC, merged